<?php
namespace App\Dto;

class CharactersDto
{
    public $gameOfThornes = [
        "jon",
        "daenerys",
        "tyrion",
        "arya",
        "sansa",
        "bran",
        "cersei",
        "jaime",
        "jorah",
        "theon",
        "samwell",
        "brienne",
        "davos",
        "melisandre",
        "sandor",
        "petyr",
        "varys",
        "robb",
        "stannis",
        "renly",
        "khal",
        "gendry",
        "joffrey",
        "margaery",
        "ramsay",
        "ygritte",
        "tormund",
        "missandei",
        "grey",
        "hodor",
        "olenna",
        "lyanna",
        "benjen",
        "rickon",
        "podrick",
        "loras",
        "shae",
        "roose",
        "barristan",
        "jeor",
        "eddard",
        "robert",
        "rhaegar",
        "jojen",
        "meera",
        "osha",
        "yara",
        "balon",
        "ellaria",
        "oberyn",
        "myrcella",
        "tommen",
        "ros",
        "lancel",
        "qyburn",
        "beric",
        "thoros",
        "hotpie",
        "daario",
        "hizdahr",
        "olly",
        "euron",
        "victarion",
        "mance",
        "osha",
        "shireen",
        "selyse",
        "gilly",
        "pyp",
        "grenn",
        "alliser",
        "maester",
        "lysa",
        "robin",
        "walder",
        "edmure",
        "brynden",
        "tywin",
        "kevan",
        "doran",
        "trystane",
        "areo",
        "nymeria",
        "obara",
        "tyene",
        "septa",
        "lancel",
        "illyrio",
        "doreah",
        "irri",
        "viserys",
        "rakharo",
        "qotho",
        "drogo",
        "syrio",
        "maester",
        "ilyn",
        "meryn",
        "bronn",
        "jaqen"
    ];

    function getRandonWithoutRepetition($characters)
    {
        $randomCharacter = $this->gameOfThornes[array_rand($this->gameOfThornes)];
        //check if the character is already in the array and if it is, get another one
        if (in_array($randomCharacter, $characters)) {
            return $this->getRandonWithoutRepetition($characters);
        }

        return $randomCharacter;
    }
}
